// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


/**
 * Level of depth for analysis operations
 */
export type AnalysisDepth = 'basic' | 'detailed' | 'comprehensive';

/**
 * Constant values for AnalysisDepth
 */
export const AnalysisDepthValues = {
  /** basic */
  BASIC: 'basic',
  /** detailed */
  DETAILED: 'detailed',
  /** comprehensive */
  COMPREHENSIVE: 'comprehensive'
} as const;