// Code generated by schema2code at 2026-03-07 19:34:27. DO NOT EDIT.


/**
 * API key for IDE and external service integration
 */
export interface ApiKey {
  /**
   * Unique identifier (UUID)
   */
  id: string;
  /**
   * User ID that owns this key
   */
  user_id: string;
  /**
   * SHA-256 hash of the actual API key (never store plaintext)
   */
  key_hash: string;
  /**
   * Human-readable name for this key
   */
  name: string;
  /**
   * When the key was created
   */
  created_at: Date;
  /**
   * When the key was last used
   */
  last_used_at?: Date;
  /**
   * When the key expires (null = never)
   */
  expires_at?: Date;
  /**
   * Whether this key has been revoked
   */
  is_revoked?: boolean;
  /**
   * API scopes this key has access to (e.g., 'chat', 'generate', 'embed')
   */
  scopes: (string)[];
}