// Code generated by schema2code at 2026-03-07 19:34:27. DO NOT EDIT.


/**
 * Response when creating an API key (includes plaintext key once)
 */
export interface ApiKeyResponse {
  /**
   * Unique identifier (UUID)
   */
  id: string;
  /**
   * User ID that owns this key
   */
  user_id: string;
  /**
   * The actual API key (returned only on creation, never stored plaintext)
   */
  key: string;
  /**
   * Human-readable name for this key
   */
  name: string;
  /**
   * When the key was created
   */
  created_at: Date;
  /**
   * When the key expires (null = never)
   */
  expires_at?: Date;
  /**
   * API scopes this key has access to (e.g., 'chat', 'generate', 'embed')
   */
  scopes: (string)[];
}