// Code generated by schema2code at 2026-03-07 19:34:27. DO NOT EDIT.


/**
 * Authentication configuration
 */
export interface AuthConfig {
  /**
   * JWKS URI
   */
  jwks_uri: string;
  /**
   * Audience
   */
  audience: string;
  /**
   * Client ID
   */
  client_id: string;
  /**
   * Client secret
   */
  client_secret: string;
}