// Code generated by schema2code at 2026-03-07 19:34:27. DO NOT EDIT.


import { RequiredCapability } from './RequiredCapability';

import { ModelProfileType } from './ModelProfileType';

import { ComplexityLevel } from './ComplexityLevel';

import { ComputationalRequirement } from './ComputationalRequirement';



/**
 * Mapping from required capabilities to appropriate model profile types
 */
export interface CapabilityProfileMapping {
  /**
   * The required capability
   */
  capability: RequiredCapability;
  /**
   * List of model profile types that can fulfill this capability
   */
  compatible_profiles: (ModelProfileType)[];
  /**
   * Preferred model profile type for this capability
   */
  preferred_profile: ModelProfileType;
  /**
   * Minimum complexity level where this capability mapping applies
   */
  minimum_complexity_level?: ComplexityLevel;
  /**
   * Computational requirements imposed by this capability
   */
  computational_requirements?: (ComputationalRequirement)[];
}