// Code generated by schema2code at 2026-03-07 19:34:27. DO NOT EDIT.


/**
 * General complexity estimation for tasks and operations
 */
export type ComplexityEstimate = 'low' | 'medium' | 'high';

/**
 * Constant values for ComplexityEstimate
 */
export const ComplexityEstimateValues = {
  /** low */
  LOW: 'low',
  /** medium */
  MEDIUM: 'medium',
  /** high */
  HIGH: 'high'
} as const;