// Code generated by schema2code at 2026-03-06 10:39:37. DO NOT EDIT.


import { ServerConfig } from './ServerConfig';

import { DatabaseConfig } from './DatabaseConfig';

import { RedisConfig } from './RedisConfig';

import { RabbitmqConfig } from './RabbitmqConfig';

import { AuthConfig } from './AuthConfig';

import { InferenceServiceConfig } from './InferenceServiceConfig';

import { SummarizationConfig } from './SummarizationConfig';

import { MemoryConfig } from './MemoryConfig';

import { PreferencesConfig } from './PreferencesConfig';

import { ModelProfileConfig } from './ModelProfileConfig';

import { ImageGenerationConfig } from './ImageGenerationConfig';

import { CircuitBreakerConfig } from './CircuitBreakerConfig';

import { GPUConfig } from './GpuConfig';

import { InternalConfig } from './InternalConfig';

import { EventStreamConfig } from './EventStreamConfig';



/**
 * Application configuration
 */
export interface Config {
  server: ServerConfig;
  database: DatabaseConfig;
  redis: RedisConfig;
  rabbitmq: RabbitmqConfig;
  auth: AuthConfig;
  inference_services: InferenceServiceConfig;
  summarization: SummarizationConfig;
  memory: MemoryConfig;
  preferences: PreferencesConfig;
  model_profiles: ModelProfileConfig;
  image_generation: ImageGenerationConfig;
  circuit_breaker: CircuitBreakerConfig;
  gpu_config: GPUConfig;
  /**
   * Log level
   */
  log_level: string;
  internal: InternalConfig;
  event_stream?: EventStreamConfig;
}