// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


/**
 * Settings to prevent container crashes during optimization
 */
export interface CrashPrevention {
  /**
   * Test memory allocation before full initialization
   */
  enable_preallocation_test: boolean;
  /**
   * Memory buffer to reserve (MB) to prevent system OOM
   */
  memory_buffer_mb: number;
  /**
   * Maximum time to wait for initialization before considering it failed
   */
  timeout_seconds: number;
  /**
   * Fall back to smaller parameters on failure
   */
  enable_graceful_degradation: boolean;
}