// Code generated by schema2code at 2026-03-07 19:34:27. DO NOT EDIT.


/**
 * Database configuration
 */
export interface DatabaseConfig {
  /**
   * Database host
   */
  host: string;
  /**
   * Database port
   */
  port: number;
  /**
   * Database user
   */
  user: string;
  /**
   * Database password
   */
  password: string;
  /**
   * Database name
   */
  dbname: string;
  /**
   * SSL mode
   */
  sslmode: string;
  /**
   * Connection string
   */
  connection_string: string;
}