// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


/**
 * A document/file attachment with metadata and content
 */
export interface Document {
  /**
   * Unique identifier for the file attachment
   */
  id?: number;
  /**
   * ID of the message this attachment belongs to
   */
  message_id: number;
  /**
   * ID of the user who uploaded this attachment
   */
  user_id: string;
  /**
   * Original filename of the attachment
   */
  filename: string;
  /**
   * MIME type of the file
   */
  content_type: string;
  /**
   * Size of the file in bytes
   */
  file_size: number;
  /**
   * File content (base64 encoded for binary files, plain text for text files)
   */
  content: string;
  /**
   * Extracted text content for searchability (null for images)
   */
  text_content?: string;
  /**
   * Timestamp when the attachment was created
   */
  created_at: Date;
  /**
   * Timestamp when the attachment was last updated
   */
  updated_at?: Date;
}