// Code generated by schema2code at 2026-03-07 19:34:27. DO NOT EDIT.


/**
 * Represents the response for an embedding request
 */
export interface EmbeddingResponse {
  model: string;
  embeddings: ((number)[])[];
  total_duration: number;
  load_duration: number;
  prompt_eval_count: number;
}