// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


/**
 * Enumeration of possible execution states for pipelines
 */
export type ExecutionState = 'INITIALIZED' | 'RUNNING' | 'COMPLETED' | 'FAILED' | 'TERMINATED';

/**
 * Constant values for ExecutionState
 */
export const ExecutionStateValues = {
  /** INITIALIZED */
  INITIALIZED: 'INITIALIZED',
  /** RUNNING */
  RUNNING: 'RUNNING',
  /** COMPLETED */
  COMPLETED: 'COMPLETED',
  /** FAILED */
  FAILED: 'FAILED',
  /** TERMINATED */
  TERMINATED: 'TERMINATED'
} as const;