// Code generated by schema2code at 2026-03-07 19:34:27. DO NOT EDIT.


/**
 * Inference service configuration
 */
export interface InferenceService {
  /**
   * Base URL for the inference service
   */
  base_url: string;
}