// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


import { RequiredCapability } from './RequiredCapability';

import { WorkflowType } from './WorkflowType';

import { ComplexityLevel } from './ComplexityLevel';

import { ResponseFormat } from './ResponseFormat';

import { TechnicalDomain } from './TechnicalDomain';

import { ComputationalRequirement } from './ComputationalRequirement';



/**
 * Detailed analysis of user intent for smart tool generation
 */
export interface IntentAnalysis {
  /**
   * Unique identifier for the analysis record
   */
  id?: number;
  /**
   * ID of the associated message this analysis belongs to
   */
  message_id?: number;
  /**
   * The specific task inferred from the user message for this analysis
   */
  task?: string;
  /**
   * Primary intent category identified from the user message
   */
  workflow_type: WorkflowType;
  /**
   * Assessed complexity level of the request
   */
  complexity_level: ComplexityLevel;
  /**
   * Set of capabilities required to fulfill the request
   */
  required_capabilities: (RequiredCapability)[];
  /**
   * Domain specificity score (0-1, higher = more domain-specific)
   */
  domain_specificity: number;
  /**
   * Reusability potential score (0-1, higher = more reusable)
   */
  reusability_potential: number;
  /**
   * Confidence in the analysis (0-1)
   */
  confidence: number;
  /**
   * Suggested response format for the user
   */
  response_format?: ResponseFormat;
  /**
   * Identified technical domain if applicable
   */
  technical_domain?: TechnicalDomain;
  /**
   * Whether this intent specifically requires tool execution
   */
  requires_tools: boolean;
  /**
   * Whether this intent requires custom/dynamic tool generation
   */
  requires_custom_tools: boolean;
  /**
   * Tool complexity score (0-1, higher = more complex tools needed)
   */
  tool_complexity_score: number;
  /**
   * Computational requirements assessment for the request
   */
  computational_requirements: ComputationalRequirement;
  /**
   * Timestamp when the analysis was created
   */
  created_at?: Date;
}