// Code generated by schema2code at 2026-03-07 19:34:27. DO NOT EDIT.


import { Message } from './Message';



/**
 * Strongly typed state for LangGraph workflows.
 */
export interface LangGraphState {
  /**
   * Sequence of messages
   */
  messages: (Message)[];
  /**
   * Latest user input
   */
  user_input: string;
  /**
   * Number of errors encountered during workflow execution
   */
  error_count: number;
  /**
   * Maximum number of iterations allowed in the workflow
   */
  max_iterations: number;
  /**
   * Current iteration count in the workflow execution
   */
  current_iteration: number;
  /**
   * List of tools or functions that have been used in the workflow
   */
  tools_used: (string)[];
  /**
   * Storage for intermediate computation results during workflow execution
   */
  intermediate_results: Record<string, unknown>;
}