// Code generated by schema2code at 2026-03-07 19:34:27. DO NOT EDIT.


/**
 * Learned maximum limits from successful configurations
 */
export interface LearnedLimits {
  /**
   * Maximum context window size learned
   */
  max_context: number;
  /**
   * Maximum batch size learned
   */
  max_batch: number;
  /**
   * Maximum GPU layers learned
   */
  max_gpu_layers: number;
  /**
   * 95th percentile of successful context sizes
   */
  context_95th_percentile: number;
  /**
   * 95th percentile of successful batch sizes
   */
  batch_95th_percentile: number;
  /**
   * 95th percentile of successful GPU layer counts
   */
  gpu_layers_95th_percentile: number;
}