// Code generated by schema2code at 2026-03-07 19:34:27. DO NOT EDIT.


import { MessageRole } from './MessageRole';



/**
 * Content item that is similar to a user's query
 */
export interface MemoryFragment {
  /**
   * Unique identifier for the memory fragment
   */
  id: number;
  /**
   * Role of the message (e.g., 'user', 'assistant')
   */
  role: MessageRole;
  /**
   * Content of the message
   */
  content?: string;
  /**
   * Embedding vector representing the memory
   */
  embeddings?: ((number)[])[];
}