// Code generated by schema2code at 2026-03-07 19:34:27. DO NOT EDIT.


/**
 * Source type for a memory
 */
export type MemorySource = 'summary' | 'message' | 'search' | 'document';

/**
 * Constant values for MemorySource
 */
export const MemorySourceValues = {
  /** summary // Memory type for conversation summaries */
  SUMMARY: 'summary',
  /** message // Memory type for conversation messages */
  MESSAGE: 'message',
  /** search // Memory type for search topic syntheses */
  SEARCH: 'search',
  /** document // Memory type for documents and file attachments */
  DOCUMENT: 'document'
} as const;