// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


import { MessageRole } from './MessageRole';

import { MessageContent } from './MessageContent';

import { Thought } from './Thought';

import { ToolCall } from './ToolCall';

import { IntentAnalysis } from './IntentAnalysis';

import { Document } from './Document';



/**
 * Message represents a single exchange in the conversation
 */
export interface Message {
  /**
   * Role of the message sender (e.g., user, assistant)
   */
  role: MessageRole;
  /**
   * Content of the message
   */
  content: (MessageContent)[];
  /**
   * Unique identifier for the message
   */
  id?: number;
  /**
   * Timestamp of when the message was created
   */
  created_at?: Date;
  /**
   * Unique identifier for the conversation
   */
  conversation_id?: number;
  /**
   * Array of thoughts or reasoning processes from the assistant
   */
  thoughts?: (Thought)[];
  /**
   * Array of tool calls associated with the message
   */
  tool_calls?: (ToolCall)[];
  /**
   * Array of intent analyses associated with the message
   */
  analyses?: (IntentAnalysis)[];
  /**
   * Array of documents attached to the message
   */
  documents?: (Document)[];
  /**
   * Structured output data from the message
   */
  structured_output?: Record<string, unknown>;
}