// Code generated by schema2code at 2026-03-07 19:34:27. DO NOT EDIT.


/**
 * ML model performance metrics for OOM recovery predictions
 */
export interface MLModelPerformance {
  /**
   * Mean squared error for context window predictions
   */
  n_ctx_mse: number;
  /**
   * Mean squared error for batch size predictions
   */
  n_batch_mse: number;
  /**
   * Mean squared error for micro-batch size predictions
   */
  n_ubatch_mse: number;
  /**
   * Mean squared error for GPU layer predictions
   */
  n_gpu_layers_mse: number;
  /**
   * Total number of configurations used for training
   */
  total_configurations: number;
  /**
   * Whether ML models have been successfully trained
   */
  models_trained: boolean;
}