// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


/**
 * ModelDetails contains additional information about a model
 */
export interface ModelDetails {
  /**
   * Identifier of the parent model if this is a derivative
   */
  parent_model?: string;
  /**
   * Format of the model file (e.g., gguf)
   */
  format: string;
  /**
   * Path to the GGUF file if applicable
   */
  gguf_file?: string;
  /**
   * Path to the CLIP model file for multimodal models (e.g., mmproj file)
   */
  clip_model_path?: string;
  /**
   * Primary model family this belongs to (e.g., llama, phi3)
   */
  family: string;
  /**
   * All model families this belongs to
   */
  families: (string)[];
  /**
   * Size of model parameters (e.g., '7.2B')
   */
  parameter_size: string;
  /**
   * Level of quantization applied to the model (e.g., 'Q4_0')
   */
  quantization_level?: string;
  /**
   * Data type of the model (e.g., 'float16', 'bfloat16')
   */
  dtype?: string;
  /**
   * Precision of the model (e.g., 'fp16', 'bf16')
   */
  precision?: 'fp32' | 'fp16' | 'bf16' | 'int8' | 'int4' | 'int2' | 'int1';
  /**
   * Specialization of the model (e.g., 'LoRA', 'Embedding', 'TextToImage', 'Audio', 'Vision')
   */
  specialization?: 'LoRA' | 'Embedding' | 'TextToImage' | 'ImageToImage' | 'Audio' | 'Text';
  /**
   * Description of the model
   */
  description?: string;
  /**
   * Weight of the model (applies to LoRA models)
   */
  weight?: number;
  /**
   * Size of the model in bytes
   */
  size: number;
  /**
   * Original context window size of the model
   */
  original_ctx: number;
  /**
   * Number of layers in the model
   */
  n_layers?: number;
  /**
   * Hidden size of the model
   */
  hidden_size?: number;
  /**
   * Number of attention heads in the model
   */
  n_heads?: number;
  /**
   * Number of key-value heads in the model
   */
  n_kv_heads?: number;
  /**
   * Size of the CLIP model in bytes, if applicable
   */
  clip_model_size?: number;
}