// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


/**
 * Configuration parameters and results for model initialization attempts
 */
export interface ModelConfigurationData {
  /**
   * Context window size used
   */
  n_ctx: number;
  /**
   * Batch size used
   */
  n_batch: number;
  /**
   * Micro-batch size used
   */
  n_ubatch: number;
  /**
   * Number of GPU layers used
   */
  n_gpu_layers: number;
  /**
   * Model size in megabytes
   */
  model_size_mb: number;
  /**
   * Available GPU memory at initialization in MB
   */
  available_gpu_memory_mb: number;
  /**
   * Total GPU memory in MB
   */
  total_gpu_memory_mb: number;
  /**
   * Whether initialization was successful
   */
  success: boolean;
  /**
   * GPU memory used after initialization in MB
   */
  gpu_memory_used_mb?: number;
  /**
   * Time taken for initialization in milliseconds
   */
  initialization_time_ms?: number;
}