// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


import { ModelProfileType } from './ModelProfileType';



/**
 * Metadata structure for workflow node execution tracking
 */
export interface NodeMetadata {
  /**
   * Human-readable name of the node
   */
  node_name: string;
  /**
   * Unique identifier for this specific node instance
   */
  node_id: string;
  /**
   * Class name of the node for type identification
   */
  node_type: string;
  execution_time?: Date;
  /**
   * User identifier associated with this execution
   */
  user_id?: string;
  /**
   * Conversation identifier for this execution context
   */
  conversation_id?: number;
  /**
   * Model profile type for pipeline execution
   */
  profile_type?: ModelProfileType;
  /**
   * Whether this execution uses streaming responses
   */
  streaming?: boolean;
  /**
   * Whether this execution uses a cached pipeline
   */
  is_cached?: boolean;
  /**
   * Cache key used for pipeline caching
   */
  cache_key?: string;
  /**
   * Number of tools available or executed
   */
  tool_count?: number;
}