// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


/**
 * Single OOM recovery attempt configuration and result
 */
export interface OOMRecoveryAttemptData {
  /**
   * Attempt number in the recovery sequence
   */
  attempt: number;
  /**
   * Recovery strategy used in this attempt
   */
  strategy: 'clear_memory' | 'reduce_batch' | 'move_to_cpu' | 'reduce_context';
  /**
   * Context window size used in this attempt
   */
  n_ctx: number;
  /**
   * Batch size used in this attempt
   */
  n_batch: number;
  /**
   * Micro-batch size used in this attempt
   */
  n_ubatch: number;
  /**
   * Number of GPU layers used in this attempt
   */
  n_gpu_layers: number;
  /**
   * Whether this attempt was successful
   */
  success: boolean;
  /**
   * Error message if the attempt failed
   */
  error_message: string;
}