// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


/**
 * Optimal parameters predicted by ML models for LLM initialization
 */
export interface OptimalParameters {
  /**
   * Context window size
   */
  n_ctx: number;
  /**
   * Batch size for processing
   */
  n_batch: number;
  /**
   * Micro-batch size
   */
  n_ubatch: number;
  /**
   * Number of model layers to place on GPU (-1 means all layers)
   */
  n_gpu_layers: number;
}