// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


/**
 * Schema defining pagination parameters and metadata for API responses
 */
export interface PaginationSchema {
  /**
   * Total number of items available
   */
  total_count: number;
  /**
   * Maximum number of items per page
   */
  limit: number;
  /**
   * Starting position of the current page
   */
  offset: number;
  /**
   * Indicates whether more items are available beyond the current page
   */
  has_more: boolean;
}