// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


/**
 * Pipeline lifecycle states for tracking execution phases
 */
export type PipelineState = 'initializing' | 'running' | 'completing' | 'terminated' | 'failed' | 'cleanup';

/**
 * Constant values for PipelineState
 */
export const PipelineStateValues = {
  /** initializing */
  INITIALIZING: 'initializing',
  /** running */
  RUNNING: 'running',
  /** completing */
  COMPLETING: 'completing',
  /** terminated */
  TERMINATED: 'terminated',
  /** failed */
  FAILED: 'failed',
  /** cleanup */
  CLEANUP: 'cleanup'
} as const;