// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


/**
 * Pipeline priority levels for cache eviction and resource management
 */
export enum PipelinePriority {
  LOW = 1,
  MEDIUM = 5,
  NORMAL = 10,
  HIGH = 11,
  CRITICAL = 20,
}