// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


/**
 * Features used for ML parameter prediction
 */
export interface PredictionFeatures {
  /**
   * Model size in megabytes
   */
  model_size_mb: number;
  /**
   * Total GPU memory across all devices in MB
   */
  total_gpu_memory_mb: number;
  /**
   * Total available GPU memory across all devices in MB
   */
  total_available_memory_mb: number;
  /**
   * Total number of GPU devices
   */
  total_gpus: number;
}