// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


/**
 * User preferences configuration
 */
export interface PreferencesConfig {
  /**
   * UI theme preference
   */
  theme?: string;
  /**
   * Preferred language
   */
  language?: string;
  /**
   * Enable notifications
   */
  notifications_on?: boolean;
  /**
   * Font size preference
   */
  font_size?: number;
}