// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


import { OptimalParameters } from './OptimalParameters';



/**
 * Recovery strategy result with optimal parameters and strategy name
 */
export interface RecoveryStrategy {
  /**
   * Optimal parameters for the strategy
   */
  parameters: OptimalParameters;
  /**
   * Name of the recovery strategy applied
   */
  strategy_name: 'clear_memory' | 'reduce_batch' | 'move_to_cpu' | 'reduce_context';
}