// Code generated by schema2code at 2025-12-01 22:30:40. DO NOT EDIT.


/**
 * Response refinement settings
 */
export interface RefinementConfig {
  /**
   * Enable response filtering
   */
  enable_response_filtering: boolean;
  /**
   * Enable response critique
   */
  enable_response_critique: boolean;
}