// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


/**
 * Current status of the research task
 */
export type ResearchTaskStatus = 'PENDING' | 'PLANNING' | 'GATHERING' | 'PROCESSING' | 'SYNTHESIZING' | 'COMPLETED' | 'FAILED' | 'CANCELED';

/**
 * Constant values for ResearchTaskStatus
 */
export const ResearchTaskStatusValues = {
  /** PENDING */
  PENDING: 'PENDING',
  /** PLANNING */
  PLANNING: 'PLANNING',
  /** GATHERING */
  GATHERING: 'GATHERING',
  /** PROCESSING */
  PROCESSING: 'PROCESSING',
  /** SYNTHESIZING */
  SYNTHESIZING: 'SYNTHESIZING',
  /** COMPLETED */
  COMPLETED: 'COMPLETED',
  /** FAILED */
  FAILED: 'FAILED',
  /** CANCELED */
  CANCELED: 'CANCELED'
} as const;