// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


/**
 * Result of processing a sub-question in a research task
 */
export interface ResearchQuestionResult {
  /**
   * Unique identifier for the question result
   */
  id: number;
  /**
   * List of sources used to gather information
   */
  sources?: (string)[];
  /**
   * Synthesized answer to the question
   */
  synthesized_answer?: string;
  /**
   * Error message if processing failed
   */
  error_message?: string;
}