// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


import { ResearchTaskStatus } from './ResearchTaskStatus';

import { ResearchSubtask } from './ResearchSubtask';



/**
 * ResearchTask represents a deep research task
 */
export interface ResearchTask {
  /**
   * Unique identifier for the research task
   */
  id: number;
  /**
   * Id of the user who owns the task
   */
  user_id: string;
  /**
   * Original research query
   */
  query: string;
  /**
   * Id of the conversation associated with this task if any
   */
  conversation_id?: number;
  /**
   * Current status of the research task
   */
  status: ResearchTaskStatus;
  /**
   * Error message if task failed
   */
  error_message?: string;
  /**
   * Research plan with sub-questions
   */
  plan?: string;
  /**
   * The reasearch plan's embedding vector
   */
  embedding?: (number)[];
  /**
   * List of subtasks associated with this research task
   */
  subtasks?: (ResearchSubtask)[];
  /**
   * Timestamp of when the task was created
   */
  created_at: Date;
  /**
   * Timestamp of when the task was last updated
   */
  updated_at: Date;
  /**
   * Timestamp of when the task was completed
   */
  completed_at?: Date;
}