// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


import { ResearchQuestion } from './ResearchQuestion';

import { ResearchQuestionResult } from './ResearchQuestionResult';

import { ResearchTaskStatus } from './ResearchTaskStatus';



/**
 * Subtask within a research task
 */
export interface ResearchSubtask {
  /**
   * Unique identifier for the subtask
   */
  id: number;
  /**
   * Id of the parent research task
   */
  task_id: number;
  /**
   * The research question this subtask addresses
   */
  question?: ResearchQuestion;
  /**
   * Synthesized result of the subtask
   */
  result?: ResearchQuestionResult;
  /**
   * Current status of the subtask
   */
  status: ResearchTaskStatus;
  /**
   * Error message if subtask failed
   */
  error_message?: string;
  /**
   * Timestamp of when the subtask was created
   */
  created_at: Date;
  /**
   * Timestamp of when the subtask was last updated
   */
  updated_at: Date;
}