// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


/**
 * Sub-question in a research plan
 */
export interface ResearchQuestion {
  /**
   * Unique identifier for the question
   */
  id: number;
  /**
   * The question to investigate
   */
  question: string;
  /**
   * Keywords relevant to the question
   */
  keywords: (string)[];
}