// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


import { GenerationState } from './GenerationState';

import { ToolCall } from './ToolCall';



/**
 * A section of a generated response
 */
export interface ResponseSection {
  /**
   * Unique identifier for this section
   */
  id: string;
  /**
   * Order in which this section appeared
   */
  order: number;
  /**
   * Timestamp when section started
   */
  startedAt: number;
  /**
   * Timestamp when section completed (state changed)
   */
  completedAt?: number;
  /**
   * Type of section based on generation state
   */
  type: GenerationState;
  /**
   * Accumulated content for this section
   */
  content?: string;
  /**
   * Tool calls for executing sections
   */
  toolCalls?: (ToolCall)[];
}