// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


import { WorkflowType } from './WorkflowType';



/**
 * Alternative routing strategy that was considered
 */
export interface AlternativeStrategy {
  workflows?: (string)[];
  strategy?: string;
  reason?: string;
  confidence?: number;
}

/**
 * Additional metadata about the routing decision
 */
export interface Metadata {
  /**
   * Identified primary workflow type from intent analysis
   */
  workflow_type?: WorkflowType;
  /**
   * Assessed complexity level
   */
  complexity_level?: 'simple' | 'medium' | 'high';
  /**
   * Whether fallback routing was applied
   */
  fallback_applied?: boolean;
  /**
   * Path of routing decisions taken
   */
  routing_path?: (string)[];
}

/**
 * Strongly typed routing strategy result containing workflow selection and execution details
 */
export interface RoutingStrategy {
  /**
   * List of workflow names selected for execution
   */
  selected_workflows: (string)[];
  /**
   * Strategy for executing the selected workflows
   */
  execution_strategy: 'single' | 'parallel' | 'series' | 'hybrid';
  /**
   * Explanation for why this routing strategy was chosen
   */
  reason: 'command_based_routing' | 'explicit_routing_decision' | 'explicit_workflow_type' | 'complex_research_series' | 'multi_agent_intent' | 'creative_intent' | 'research_intent' | 'default_chat' | 'error_fallback';
  /**
   * Confidence score for the routing decision (0.0 to 1.0)
   */
  confidence?: number;
  /**
   * Additional metadata about the routing decision
   */
  metadata?: Metadata;
  /**
   * Target node name for LangGraph conditional routing
   */
  target_node?: string;
  /**
   * Alternative routing strategies that were considered
   */
  alternatives?: (AlternativeStrategy)[];
}