// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


/**
 * Content item from a web search result
 */
export interface SearchResultContent {
  /**
   * URL of the content
   */
  url: string;
  /**
   * Title of the content
   */
  title: string;
  /**
   * Snippet or summary of the content
   */
  content: string;
  /**
   * Relevance score of the content
   */
  relevance?: number;
}