// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


/**
 * Server configuration
 */
export interface ServerConfig {
  /**
   * Server host
   */
  host: string;
  /**
   * Server port
   */
  port: number;
  /**
   * Base URL
   */
  base_url: string;
}