// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


/**
 * Types of summaries supported by the SummarizationAgent
 */
export type SummaryType = 'primary' | 'master' | 'brief' | 'key_points';

/**
 * Constant values for SummaryType
 */
export const SummaryTypeValues = {
  /** primary */
  PRIMARY: 'primary',
  /** master */
  MASTER: 'master',
  /** brief */
  BRIEF: 'brief',
  /** key_points */
  KEY_POINTS: 'key_points'
} as const;