// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


/**
 * Styles of summaries supported by the SummarizationAgent
 */
export type SummaryStyle = 'concise' | 'detailed' | 'bullet_points' | 'structured';

/**
 * Constant values for SummaryStyle
 */
export const SummaryStyleValues = {
  /** concise */
  CONCISE: 'concise',
  /** detailed */
  DETAILED: 'detailed',
  /** bullet_points */
  BULLET_POINTS: 'bullet_points',
  /** structured */
  STRUCTURED: 'structured'
} as const;