// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


import { DevStats } from './DevStats';



/**
 * System-wide GPU statistics for dynamic multi-GPU systems
 */
export interface SystemGPUStats {
  /**
   * Total number of GPU devices in the system
   */
  total_gpus: number;
  /**
   * Total GPU memory across all devices in MB
   */
  total_memory: number;
  /**
   * Total available GPU memory across all devices in MB
   */
  total_available_memory: number;
  /**
   * List of individual GPU device information
   */
  gpus: (DevStats)[];
}