// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


/**
 * Technical domains for specialized engineering responses
 */
export type TechnicalDomain = 'software_development' | 'system_architecture' | 'data_engineering' | 'devops_infrastructure' | 'security_engineering' | 'machine_learning' | 'programming' | 'general_engineering' | 'mechanical_engineering' | 'electrical_engineering' | 'civil_engineering' | 'chemical_engineering' | 'aerospace_engineering' | 'industrial_engineering' | 'environmental_engineering' | 'biomedical_engineering';

/**
 * Constant values for TechnicalDomain
 */
export const TechnicalDomainValues = {
  /** software_development */
  SOFTWARE_DEVELOPMENT: 'software_development',
  /** system_architecture */
  SYSTEM_ARCHITECTURE: 'system_architecture',
  /** data_engineering */
  DATA_ENGINEERING: 'data_engineering',
  /** devops_infrastructure */
  DEVOPS_INFRASTRUCTURE: 'devops_infrastructure',
  /** security_engineering */
  SECURITY_ENGINEERING: 'security_engineering',
  /** machine_learning */
  MACHINE_LEARNING: 'machine_learning',
  /** programming */
  PROGRAMMING: 'programming',
  /** general_engineering */
  GENERAL_ENGINEERING: 'general_engineering',
  /** mechanical_engineering */
  MECHANICAL_ENGINEERING: 'mechanical_engineering',
  /** electrical_engineering */
  ELECTRICAL_ENGINEERING: 'electrical_engineering',
  /** civil_engineering */
  CIVIL_ENGINEERING: 'civil_engineering',
  /** chemical_engineering */
  CHEMICAL_ENGINEERING: 'chemical_engineering',
  /** aerospace_engineering */
  AEROSPACE_ENGINEERING: 'aerospace_engineering',
  /** industrial_engineering */
  INDUSTRIAL_ENGINEERING: 'industrial_engineering',
  /** environmental_engineering */
  ENVIRONMENTAL_ENGINEERING: 'environmental_engineering',
  /** biomedical_engineering */
  BIOMEDICAL_ENGINEERING: 'biomedical_engineering'
} as const;