// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


import { AnalysisDepth } from './AnalysisDepth';



/**
 * Request for analyzing if tools are needed for a user message
 */
export interface ToolAnalysisRequest {
  /**
   * The user's message text to analyze
   */
  user_message: string;
  /**
   * ID of the conversation context
   */
  conversation_id: number;
  /**
   * Depth of analysis to perform
   */
  analysis_depth?: AnalysisDepth;
}