// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


/**
 * Schema representing a LangChain BaseTool with its properties and configuration
 */
export interface Tool {
  /**
   * The unique name of the tool that clearly communicates its purpose
   */
  name: string;
  /**
   * Used to tell the model how/when/why to use the tool. You can provide few-shot examples as a part of the description
   */
  description: string;
  /**
   * Pydantic model class to validate and parse the tool's input arguments
   */
  args_schema?: unknown | Record<string, unknown> | string;
  /**
   * Whether to return the tool's output directly. Setting this to True means that after the tool is called, the AgentExecutor will stop looping
   */
  return_direct?: boolean;
  /**
   * Optional list of tags associated with the tool. These tags will be associated with each call to this tool and passed as arguments to the handlers defined in callbacks
   */
  tags?: (string)[];
  /**
   * Optional metadata associated with the tool. This metadata will be associated with each call to this tool and passed as arguments to the handlers defined in callbacks
   */
  metadata?: Record<string, unknown>;
  /**
   * Handle the content of the ToolException thrown. Can be a boolean, string, or callable function
   */
  handle_tool_error?: boolean | string | unknown;
  /**
   * Handle the content of the ValidationError thrown. Can be a boolean, string, or callable function
   */
  handle_validation_error?: boolean | string | unknown;
  /**
   * The tool response format. If 'content' then the output is interpreted as ToolMessage contents. If 'content_and_artifact' then output is expected to be a two-tuple of (content, artifact)
   */
  response_format?: 'content' | 'content_and_artifact';
}