// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


import { DynamicTool } from './DynamicTool';



/**
 * Schema for tool needs analysis
 */
export interface ToolNeeds {
  /**
   * List of available tool names
   */
  available_tools: (string)[];
  needs_dynamic_tool: boolean;
  dynamic_tool?: DynamicTool;
}