// Code generated by schema2code at 2026-03-07 19:34:28. DO NOT EDIT.


/**
 * Supported workflow types for composer orchestration.

 */
export type WorkflowType = 'general' | 'research' | 'engineering' | 'creative' | 'image_generation' | 'image_refinement' | 'analysis' | 'planning' | 'focused';

/**
 * Constant values for WorkflowType
 */
export const WorkflowTypeValues = {
  /** general */
  GENERAL: 'general',
  /** research */
  RESEARCH: 'research',
  /** engineering */
  ENGINEERING: 'engineering',
  /** creative */
  CREATIVE: 'creative',
  /** image_generation */
  IMAGE_GENERATION: 'image_generation',
  /** image_refinement */
  IMAGE_REFINEMENT: 'image_refinement',
  /** analysis */
  ANALYSIS: 'analysis',
  /** planning */
  PLANNING: 'planning',
  /** focused */
  FOCUSED: 'focused'
} as const;